version: '3.1'
services:
  keycloak:
    image: jboss/keycloak:9.0.2
    networks:
      - database
      - gazeauth
    ports:
      - "127.0.0.1:8081:8080"
    env_file:
      - variables-local.env
    volumes:
      - ./themes/gaze:/opt/jboss/keycloak/themes/gaze
      - ./themes/housingdb:/opt/jboss/keycloak/themes/housingdb
    depends_on:
      - postgres
  postgres:
    image: postgres:10
    volumes:
      - ./docker/postgres-data:/var/lib/postgresql/data
    env_file:
      - variables-local.env
    ports:
      - "5435:5432"
    networks:
      - database
networks:
  database:
    driver: bridge
  gazeauth:
    driver: bridge
